language: python
branches:
  only:
    - master
python: 3.7
dist: xenial
sudo: true
services:
  - docker
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - ./scripts/test.sh
after_success:
  - heroku login
  - heroku container:login
  - heroku container:push web
  - heroku container:release web
