language: python
branches:
  only:
    - master
python: 3.7
dist: xenial
sudo: true
services:
  - docker
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - ./scripts/test.sh
# deploy:
#   provider: script
#   script: ./scripts/deploy.sh
after_success:
  - docker login -u _ -p "$HEROKU_API_KEY"  registry.heroku.com
  - docker build -t registry.heroku.com/sliceurl/web -f Dockerfile .
  - docker push registry.heroku.com/sliceurl/web
  - heroku run --app sliceurl
