language: python
branches:
  only:
    - master
python: 3.7
dist: xenial
sudo: true
services:
  - docker
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - ./scripts/test.sh
# deploy:
#   provider: script
#   script: ./scripts/deploy.sh
after_success:
  - docker login -u _ -p "$HEROKU_API_KEY"  registry.heroku.com
  - docker build -t registry.heroku.com/sliceurl/web -f Dockerfile .
  - docker push registry.heroku.com/sliceurl/web
  - heroku run --app sliceurl
  - image_id=$(docker inspect registry.heroku.com/sliceurl/web --format={{.Id}})
  - payload='{"updates":[{"type":"web","docker_image":"'"$image_id"'"}]}'
  - curl -n -X PATCH https://api.heroku.com/apps/sliceurl/formation -d "$payload" -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases" -H "Authorization: Bearer $HEROKU_API_KEY"
