name: CI
on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          docker build -t test -f ./docker/test.Dockerfile .
          docker run test
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com
          docker build -t registry.heroku.com/sliceurl/web -f ./docker/Dockerfile .
          docker push registry.heroku.com/sliceurl/web
          IMAGE_ID=$(docker inspect registry.heroku.com/sliceurl/web --format={{.Id}})
          PAYLOAD='{"updates":[{"type":"web","docker_image":"'"${IMAGE_ID}"'"}]}'
          curl -n -X PATCH https://api.heroku.com/apps/sliceurl/formation \
               -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
               -H "Authorization: Bearer $HEROKU_API_KEY" \
               -H "Content-Type: application/json" \
               -d "${PAYLOAD}"
