name: CI
on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          docker build -t test -f ./docker/test.Dockerfile .
          docker run test
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile: docker/Dockerfile
          email: ${{ secrets.HEROKU_EMAIL }}
